version: '3'
services:
  db:
    image: mongo:3.0.2
  api:
    build: api
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
  app:
    build: app
    ports:
      - "3000:3000"
    depends_on:
      - api
